version: "3"

services:
  db:
    image: mdillon/postgis:10-alpine
    volumes:
      - ./data/postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: froide
      POSTGRES_DB: froide
      POSTGRES_PASSWORD: froide
    ports:
      - "127.0.0.1:5432:5432"
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.1
    volumes:
      - ./data/elasticsearch-data:/usr/share/elasticsearch/data
      - ./data/elasticsearch-log:/var/log
    environment:
      - "discovery.type=single-node"
      - "cluster.routing.allocation.disk.threshold_enabled=false"
      - "cluster.routing.allocation.disk.watermark.low=3gb"
      - "cluster.routing.allocation.disk.watermark.high=2gb"
      - "cluster.routing.allocation.disk.watermark.flood_stage=1gb"
    ports:
      - "127.0.0.1:9200:9200"
